# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078d65ebbf2d2469202e96538dafadc64583af7e2d687e6041ce6a1ecfe6a0ac820a52f4d9e8e243198e087ba0f8cce473b8a1979d18292f6e8be6a7a5fd7cd5

test:
  secret_key_base: a276f7b3192c878170c729172dc8149e5aa71f9656868d65c87efc4add504f326233d2cca1449518d6082d92b55971cd4d18f5c3d2493c96dda9c191acb90697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
